name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: astral-sh/setup-uv@v3
      - name: Build sdist and wheel with uv
        run: |
          uv build
          ls -l dist
      - name: Publish to PyPI (token or OIDC)
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
          packages-dir: dist
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
