name: release

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: astral-sh/setup-uv@v3
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Install commitizen and gh
        run: |
          uv sync --dev
          sudo apt-get update && sudo apt-get install -y gh
      - name: Bump version and changelog if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run cz bump --changelog --yes || echo "No version bump"
      - name: Push tags
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure tags are pushed explicitly; some runners miss annotated tags with --follow-tags
          git push origin HEAD:main
          git push origin --tags
      - name: Create GitHub Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || true)
          if [ -n "$LATEST_TAG" ]; then \
            gh release create "$LATEST_TAG" -F CHANGELOG.md -t "$LATEST_TAG" --latest || true; \
          fi
